# Generated by Django 4.1.5 on 2023-04-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0041_remove_supervisor_phone_no_remove_teammember_phoneno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=125)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
